### ISSUE TITLE
Get a notification "Unable to connect to ..." every time the connection is lost

### ISSUE THREAD

**Issue by roblourens** [jlandersen/vscode-vsts-build-status#13]
I keep getting a notification when leaving wifi, which is annoying and not necessary. Also it would be great if the status bar item would refresh itself when I have a connection again.

**Comment by jlandersen** [comment]
Thanks for the feedback! I'll add some proper handling of this

**Comment by jlandersen** [comment]
I made a few changes, so that instead of stopping completely and showing an error message, it will show "connecting" and continue to run in the background. An error message is only displayed if the first fetch fails after starting VS Code or changing your settings. 

Will push it to marketplace within the next few days!
